version: '3'

services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./config/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      default:
      emotives:
        aliases:
          - postgres_db

volumes:
  postgres-data:

networks:
  emotives:
    external:
      name: emotives
  default:
